import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';

export default function About() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <section className="hero">
          <div className="copyblock">
            <h1>About us</h1>
            <h2>It's nothing</h2>
          </div>
        </section>
      </main>
    </div>
  );
}
