import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import { ButtonSecondary, ButtonPrimary } from '../components/Buttons';
import Card from '../components/Cards';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="container mx-auto">
        <section className="hero">
          <div className="copyblock">
            <h1 className="text-3xl font-bold underline ">
              The best product in the world
            </h1>
            <ButtonPrimary text="Siia peab primaarselt vajutama" />
            <ButtonSecondary text="Siia peab vajutama" />
          </div>

          <Card
            header="See on päis"
            body="see on sisu"
            link="/"
            linktext="mine koju"
          />
          <picture>
            <img src="./images/city.jpg" alt="city" />
          </picture>
          <div className="gradient-overlay"></div>
        </section>
        <section className="copy">
          <div className="copyblock">
            <h2>Really good product</h2>
            <p>Using this product makes you feel good</p>
          </div>
        </section>
        <section id="products" className="products">
          <div className="copyblock">
            <h2>Shop now</h2>
            <p>Choose the most suitable product</p>
          </div>
          <div className="holdcontent">
            <a href="./product.html" className="product">
              <div className="holdproduct">
                <div className="img">
                  <img src="./images/city2.jpg" alt="city 2" />
                </div>
                <div className="title">
                  <h4>Product 2</h4>
                </div>
              </div>
            </a>
            <a href="./product.html" className="product">
              <div className="holdproduct">
                <div className="img">
                  <img src="./images/city3.jpg" alt="city 3" />
                </div>
                <div className="title">
                  <h4>Product 2</h4>
                </div>
              </div>
            </a>
            <a href="./product.html" className="product">
              <div className="holdproduct">
                <div className="img">
                  <img src="./images/city4.jpg" alt="city 4" />
                </div>
                <div className="title">
                  <h4>Product 2</h4>
                </div>
              </div>
            </a>
          </div>
          <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
            Button
          </button>
        </section>
      </main>
    </div>
  );
}
